version: "3.8"

services:
  ubuntuclient1:
    image: umutgyk/ubuntuclient
    cap_add:
      - NET_ADMIN
    hostname: ubuntuclient
    networks:
      gateway1-internal:
        ipv4_address: 172.18.0.3
    command: >-
      sh -c "
      ip route del default &&
      ip route add default via 172.18.0.2 &&
      tail -f /dev/null"
      
  gateway1:
    image: umutgyk/ubuntuclient
    cap_add:
      - NET_ADMIN
    hostname: gateway1
    networks:
      gateway1-internal:
        ipv4_address: 172.18.0.2
      mybridge:
        ipv4_address: 172.20.0.3
    command: >-
      sh -c "iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE --random &&
      iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE --random &&
      iptables -A FORWARD -i eth1 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT &&
      iptables -A FORWARD -i eth0 -o eth1 -m state --state RELATED,ESTABLISHED -j ACCEPT &&
      ip route del default &&
      ip route add default via 172.18.0.2 &&
      ip route add 172.19.0.0/16 via 172.20.0.2 &&
      tail -f /dev/null"


  gateway2:
    image: umutgyk/ubuntuclient
    cap_add:
      - NET_ADMIN
    hostname: gateway2
    networks:
      gateway2-internal:
        ipv4_address: 172.19.0.2
      mybridge:
        ipv4_address: 172.20.0.4
    command: >-
      sh -c "iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE --random &&
      iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE --random &&
      iptables -A FORWARD -i eth1 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT &&
      iptables -A FORWARD -i eth0 -o eth1 -m state --state RELATED,ESTABLISHED -j ACCEPT &&
      ip route add 172.18.0.0/16 via 172.20.0.2 &&
      tail -f /dev/null"

  ubuntuclient2:
    image: umutgyk/ubuntuclient
    cap_add:
      - NET_ADMIN
    hostname: ubuntuclient2
    
    networks:
      gateway2-internal:
        ipv4_address: 172.19.0.3
    command: >-
      sh -c "iptables -A OUTPUT -p all -j ACCEPT &&
      iptables -A INPUT -p all -j ACCEPT &&
      iptables -A FORWARD -p all -j ACCEPT &&
      ip route del default &&
      ip route add default via 172.19.0.2 &&
      tail -f /dev/null"
  
  ubuntuclient3:
    image: umutgyk/ubuntuclient
    cap_add:
      - NET_ADMIN
    hostname: ubuntuclient3
    networks:
      mybridge:
        ipv4_address: 172.20.0.5
    command: >-
      sh -c "
      ip route del default &&
      ip route add default via 172.20.0.2 &&
      tail -f /dev/null"

  turnserver:
    image: umutgyk/turnserver
    cap_add:
      - NET_ADMIN
    ports:
# STUN/TURN
      - "3478:3478"
      - "3478:3478/udp"
      - "3479:3479"
      - "3479:3479/udp"
      - "80:80"
      - "80:80/udp"
# STUN/TURN SSL
      - "5349:5349"
      - "5349:5349/udp"
      - "5350:5350"
      - "5350:5350/udp"
      - "443:443"
      - "443:443/udp"
    networks:
      mybridge:
        ipv4_address: 172.20.0.2
    restart: always
    command: >-
      sh -c "iptables -A FORWARD -i eth0 -p all -j ACCEPT &&
      iptables -A FORWARD -i eth1 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT &&
      turnadmin -a -u $turnuser -p $userpwd -r $realm -b "/usr/share/coturn/turnuserdb.conf" && 
      bash deploy-turnserver.sh $realm -L 127.0.0.1 -L ::1 -E 127.0.0.1 -E ::1"
      
networks:
  gateway1-internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
  gateway2-internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
  mybridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
